### PR TITLE
fix: rendering of multiple Vue components on the same page

### PR DESCRIPTION
**Pull request by muryoh**
Clearly this code was here for a reason, but it was not working when trying to render multiple components on the same page
@gqio mentioned it was because components were not being updated when the code was modified, but I wasn't able to reproduce it

Anybody remembers the exact use case?

### CODE REVIEW

**Comment by georges-gomes** [comment]
In Vue 3 you need to unmount the app before mounting a new one. Otherwise it can't switch from one story to another for components with multiple stories.

Is it working now without the unmount I don't know but it may be sub-optimal

**Comment by gluck** [comment]
This code triggers a warning in vue3 dev (something about mounting a component with no template)

**Comment by gluck** [comment]
So I'm in favor of getting rid of it, I'll try it in vite one released

**Comment by muryoh** [comment]
> In Vue 3 you need to unmount the app before mounting a new one. Otherwise it can't switch from one story to another for components with multiple stories.
> 
> Is it working now without the unmount I don't know but it may be sub-optimal

Couldn't find any reference for this, do you remember maybe why?
But yes I tried without it and it was working

**Comment by gluck** [comment]
https://github.com/divriots/universal-story-render/pull/3 goes even further

**Comment by georges-gomes** [comment]
> > In Vue 3 you need to unmount the app before mounting a new one. Otherwise it can't switch from one story to another for components with multiple stories.
> > Is it working now without the unmount I don't know but it may be sub-optimal
> 
> Couldn't find any reference for this, do you remember maybe why?
> But yes I tried without it and it was working

I experienced it. Maybe the latest Vue fixes it which is good 👍

**Pull request closed without merging**
