### PR TITLE
Update SolidJS renderer

### PR DESCRIPTION
**Pull request by m4dz**

### CODE REVIEW

**Review by gluck — APPROVED** [review]

**Comment by gluck** [comment]
Update the doc as well?

**Review by gqio — APPROVED** [review]

**Comment by m4dz** [comment]
So, if I follow the existing documentation:

```jsx
import { Button } from '..';

export const button = () => () => <Button>Hello Rioters 🤘 !</Button>;
```

renders the story ; but 

```jsx
import { Button } from '..';

export const button = () => Button;
```

isn't (returns `function () { [native code] }`).

The detection in this second case isn't working.

I suggest we merge this one as it's compliant with solidjs documentation, and we try to fix the second syntax later, I can't really figure out how to do it right now.

@gluck @gqio right for you?

**Review by gluck — APPROVED** [review]
LGTM

**Comment by gqio** [comment]
Please do not forget to publish the new version. Maybe with a minor version because it's a breaking change here

**Comment by m4dz** [comment]
> Please do not forget to publish the new version. Maybe with a minor version because it's a breaking change here

Oups, already done as a patch, and in the editor https://github.com/divriots/webcomponents-editor/pull/3743/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R185

**Pull request merged**
